#-------------------------------------#
#       use gnu c-compiler			  #
#       Makefile for Linux            #
#-------------------------------------#



CC = gcc
CFLAGS = -g

#
#	compiler flag:
#		-g : --enable to debug

calc1: calc1.c
	$(CC) $(CFLAGS) -o calc1 calc1.c

clean:
	rm -f calc1